"use client";

import * as React from "react";
import { useRouter } from "next/navigation";
import { Button } from "@/components/ui/Button";
import { KeyRound, ArrowRight, Sparkles, AlertCircle } from "lucide-react";

export function AccessCodeInput() {
  const router = useRouter();
  const [code, setCode] = React.useState("");
  const [isLoading, setIsLoading] = React.useState(false);
  const [error, setError] = React.useState<string | null>(null);

  const handleAccess = (codeToSubmit: string) => {
    const formatted = codeToSubmit.trim().toUpperCase();
    if (!formatted) return;

    setError(null);
    setIsLoading(true);

    setTimeout(() => {
      setIsLoading(false);
      // Valid mock codes
      if (formatted === "MED-7K29X" || formatted === "MED-DEMO" || formatted.startsWith("MED-")) {
        router.push("/doctor/patients/patient-001");
      } else {
        setError("Invalid or expired patient access code. Please check with your patient.");
      }
    }, 450);
  };

  const handleFillDemoCode = () => {
    setCode("MED-7K29X");
    setError(null);
  };

  return (
    <div className="bg-white rounded-2xl border border-slate-200/90 p-6 sm:p-8 shadow-xs space-y-4">
      <div className="space-y-1">
        <div className="inline-flex items-center gap-1.5 px-3 py-0.5 rounded-full bg-cyan-50 text-cyan-800 text-xs font-semibold border border-cyan-100">
          <KeyRound className="w-3.5 h-3.5 text-cyan-600" />
          <span>Patient Record Authorization</span>
        </div>
        <h2 className="text-lg sm:text-xl font-bold text-[#0F172A] tracking-tight">
          Enter Patient Access Code
        </h2>
        <p className="text-xs sm:text-sm text-slate-500 leading-relaxed">
          Enter the temporary access code generated by the patient to unlock their consolidated medical history and AI briefing.
        </p>
      </div>

      <form
        onSubmit={(e) => {
          e.preventDefault();
          handleAccess(code);
        }}
        className="space-y-3.5"
      >
        <div className="flex flex-col sm:flex-row gap-3">
          <div className="relative flex-1">
            <input
              type="text"
              value={code}
              onChange={(e) => setCode(e.target.value.toUpperCase())}
              placeholder="e.g. MED-7K29X"
              className="w-full font-mono uppercase tracking-widest text-base sm:text-lg font-bold px-4 py-2.5 bg-slate-50 border border-slate-200 rounded-xl focus:outline-none focus:ring-2 focus:ring-[#0F9D94] focus:bg-white transition-all text-[#0F172A] placeholder:text-slate-400 placeholder:font-normal placeholder:tracking-normal placeholder:text-sm shadow-2xs"
            />
          </div>

          <Button
            type="submit"
            isLoading={isLoading}
            className="sm:w-auto px-6 h-11 text-xs sm:text-sm font-semibold shadow-xs"
          >
            <span>Access Patient</span>
            <ArrowRight className="w-4 h-4 ml-1" />
          </Button>
        </div>

        {error && (
          <div className="flex items-center gap-2 text-xs text-rose-700 bg-rose-50 border border-rose-200 p-3.5 rounded-xl animate-in fade-in">
            <AlertCircle className="w-4 h-4 shrink-0" />
            <span>{error}</span>
          </div>
        )}

        {/* Demo Fast Fill Pill */}
        <div className="flex items-center justify-between text-xs text-slate-500 pt-1">
          <button
            type="button"
            onClick={handleFillDemoCode}
            className="inline-flex items-center gap-1.5 text-[#0F9D94] hover:text-[#0D8B83] font-semibold hover:underline cursor-pointer"
          >
            <Sparkles className="w-3.5 h-3.5" />
            <span>Auto-fill Demo Code (MED-7K29X)</span>
          </button>
          <span className="text-slate-400 text-[11px] font-mono">Format: MED-XXXXX</span>
        </div>
      </form>
    </div>
  );
}
